import type { Language } from './i18n';
const words = {
 startRecording:['Präsentation starten','Start presentation','Iniciar presentación','Démarrer la présentation'],
 recordReadyHint:['Warte, bis der Vollbild-Hinweis verschwunden ist. Starte dann den Countdown mit Play.','Wait until the fullscreen notice disappears, then press Play to start the countdown.','Espera a que desaparezca el aviso de pantalla completa y pulsa Play para iniciar la cuenta atrás.','Attendez que l’avis de plein écran disparaisse, puis appuyez sur Play pour lancer le compte à rebours.'],
 wakeActive:['Bildschirm wird während der Wiedergabe wach gehalten.','Screen stays awake during playback.','La pantalla permanece activa durante la reproducción.','L’écran reste éveillé pendant la lecture.'],
 wakeUnavailable:['Bildschirm-Wachhalten ist nicht verfügbar oder wurde abgelehnt. Bitte den Ruhezustand für die Aufnahme in den Geräteeinstellungen deaktivieren.','Keeping the screen awake is unavailable or was denied. Please disable screen sleep in your device settings for recording.','No se puede mantener la pantalla activa. Desactiva el reposo en los ajustes del dispositivo para grabar.','Le maintien de l’écran éveillé est indisponible ou refusé. Désactivez la veille dans les réglages de l’appareil pour enregistrer.'],
 heading:['Deine Geschichte. Deine Bühne.','Your story. Your stage.','Tu historia. Tu escenario.','Votre histoire. Votre scène.'],
 intro:['Erstelle animierte Szenen, importiere KI-Entwürfe und nimm die Fokusansicht mit deinem Screenrecorder auf.','Create animated scenes, import AI drafts and record the focus view with your screen recorder.','Crea escenas animadas, importa borradores de IA y graba la vista de enfoque.','Créez des scènes animées, importez des brouillons IA et enregistrez la vue de présentation.'],
 new:['Neues Projekt','New project','Nuevo proyecto','Nouveau projet'],load:['Laden','Load','Cargar','Charger'],save:['Speichern unter','Save as','Guardar como','Enregistrer sous'],json:['JSON importieren / kopieren','Import / copy JSON','Importar / copiar JSON','Importer / copier JSON'],ai:['Anleitung für KI','AI guide','Guía para IA','Guide IA'],
 project:['Projekt','Project','Proyecto','Projet'],title:['Titel','Title','Título','Titre'],format:['Format','Format','Formato','Format'],landscape:['Querformat · 16:9','Landscape · 16:9','Horizontal · 16:9','Paysage · 16:9'],portrait:['Hochkant · 9:16','Portrait · 9:16','Vertical · 9:16','Portrait · 9:16'],square:['Quadratisch · 1:1','Square · 1:1','Cuadrado · 1:1','Carré · 1:1'],
 scenes:['Szenen','Scenes','Escenas','Scènes'],addScene:['Szene hinzufügen','Add scene','Añadir escena','Ajouter une scène'],duplicate:['Duplizieren','Duplicate','Duplicar','Dupliquer'],remove:['Löschen','Delete','Eliminar','Supprimer'],up:['Nach oben','Move up','Subir','Monter'],down:['Nach unten','Move down','Bajar','Descendre'],
 preview:['Vorschau','Preview','Vista previa','Aperçu'],play:['Ab hier abspielen','Play from here','Reproducir desde aquí','Lire à partir d’ici'],pause:['Pause','Pause','Pausa','Pause'],reset:['Zurück zur Szene','Back to scene','Volver a la escena','Retour à la scène'],focus:['Aufnahmeansicht','Recording view','Vista de grabación','Vue d’enregistrement'],exit:['Beenden · Esc','Exit · Esc','Salir · Esc','Quitter · Échap'],
 safe:['Sichere Textbereiche anzeigen','Show safe text areas','Mostrar zonas seguras','Afficher les zones sûres'],safeHint:['Orientierung, keine plattformgenaue Garantie.','Guideline, not a platform-specific guarantee.','Orientación, no garantía por plataforma.','Repère, pas une garantie par plateforme.'],
 scene:['Szene','Scene','Escena','Scène'],name:['Name','Name','Nombre','Nom'],duration:['Dauer (Sekunden)','Duration (seconds)','Duración (segundos)','Durée (secondes)'],background:['Hintergrundfarbe','Background color','Color de fondo','Couleur de fond'],backgroundAsset:['Hintergrundbild','Background image','Imagen de fondo','Image de fond'],transition:['Szenenübergang','Scene transition','Transición','Transition'],transitionDuration:['Übergangsdauer (Sekunden)','Transition duration (seconds)','Duración de transición (segundos)','Durée de transition (secondes)'],
 elements:['Elemente','Elements','Elementos','Éléments'],text:['Text','Text','Texto','Texte'],image:['Bild','Image','Imagen','Image'],shape:['Form','Shape','Forma','Forme'],none:['Keine','None','Ninguna','Aucun'],
 asset:['Bilddatei','Image asset','Imagen','Image'],importImage:['Bild importieren','Import image','Importar imagen','Importer une image'],assets:['Bilder im Projekt','Project images','Imágenes del proyecto','Images du projet'],imageHint:['PNG, JPEG oder WebP · maximal 8 MiB pro Bild. Bilder werden in die JSON-Datei eingebettet.','PNG, JPEG or WebP · max 8 MiB per image. Images are embedded in the JSON file.','PNG, JPEG o WebP · máximo 8 MiB por imagen. Las imágenes se incluyen en el JSON.','PNG, JPEG ou WebP · 8 Mio maximum par image. Les images sont intégrées au JSON.'],
 x:['X (%)','X (%)','X (%)','X (%)'],y:['Y (%)','Y (%)','Y (%)','Y (%)'],width:['Breite (%)','Width (%)','Ancho (%)','Largeur (%)'],height:['Höhe (%)','Height (%)','Alto (%)','Hauteur (%)'],color:['Farbe','Color','Color','Couleur'],font:['Schriftart','Font','Fuente','Police'],fontSize:['Schriftgröße (Projektpixel)','Font size (project pixels)','Tamaño (píxeles del proyecto)','Taille (pixels du projet)'],align:['Ausrichtung','Alignment','Alineación','Alignement'],left:['Links','Left','Izquierda','Gauche'],center:['Zentriert','Center','Centro','Centre'],right:['Rechts','Right','Derecha','Droite'],bold:['Fett','Bold','Negrita','Gras'],opacity:['Deckkraft (0–1)','Opacity (0–1)','Opacidad (0–1)','Opacité (0–1)'],rotation:['Drehung (Grad)','Rotation (degrees)','Rotación (grados)','Rotation (degrés)'],radius:['Eckenradius (Projektpixel)','Corner radius (project pixels)','Radio (píxeles del proyecto)','Rayon (pixels du projet)'],fit:['Bildanpassung','Image fit','Ajuste de imagen','Ajustement de l’image'],cover:['Füllend','Cover','Cubrir','Couvrir'],contain:['Vollständig','Contain','Contener','Contenir'],animation:['Animation','Animation','Animación','Animation'],at:['Start (Sekunden)','Start (seconds)','Inicio (segundos)','Début (secondes)'],animationDuration:['Animationsdauer (Sekunden)','Animation duration (seconds)','Duración de animación (segundos)','Durée d’animation (secondes)'],
 fade:['Einblenden','Fade in','Aparecer','Fondu'], 'slide-left':['Von rechts','From right','Desde la derecha','Depuis la droite'],'slide-up':['Von unten','From below','Desde abajo','Depuis le bas'],zoom:['Vergrößern','Zoom in','Acercar','Zoom avant'],typewriter:['Schreibmaschine','Typewriter','Máquina de escribir','Machine à écrire'],pan:['Langsame Vergrößerung','Slow zoom','Zoom lento','Zoom lent'],
 import:['Importieren','Import','Importar','Importer'],copy:['Kopieren','Copy','Copiar','Copier'],close:['Schließen','Close','Cerrar','Fermer'],jsonHint:['Hier den KI-Entwurf einfügen. Import ersetzt das aktuelle Projekt erst nach erfolgreicher Prüfung.','Paste your AI draft here. Import replaces the current project only after validation.','Pega el borrador IA aquí. Se sustituye el proyecto tras validarlo.','Collez le brouillon IA ici. Le projet est remplacé uniquement après validation.'],
 unsaved:['Ungespeicherte Änderungen verwerfen?','Discard unsaved changes?','¿Descartar cambios sin guardar?','Abandonner les modifications non enregistrées ?'],saved:['Projektdatei zum Download bereitgestellt.','Project file prepared for download.','Archivo preparado para descargar.','Fichier préparé pour le téléchargement.'],copied:['Kopiert.','Copied.','Copiado.','Copié.'],error:['Bitte prüfen:','Please check:','Revisa:','Veuillez vérifier :'],changed:['Ungespeicherte Änderungen','Unsaved changes','Cambios sin guardar','Modifications non enregistrées'],ready:['Bereit','Ready','Listo','Prêt'],empty:['Element hinzufügen oder auswählen.','Add or select an element.','Añade o selecciona un elemento.','Ajoutez ou sélectionnez un élément.'],
 recordHint:['In der Aufnahmeansicht Play anklicken: 3 Sekunden Countdown. Danach startet das gesamte Projekt. Leertaste pausiert, Esc beendet. Maus bewegen oder tippen zeigt den Beenden-Button. Das Tool zeichnet selbst nicht auf.','Click Play in recording view: 3-second countdown, then the entire project plays. Space pauses, Esc exits. Move the mouse or tap to show the exit button. This tool does not record video itself.','Pulsa Play en la vista de grabación: cuenta atrás de 3 segundos. Espacio pausa, Esc sale. Mueve el ratón o toca para mostrar el botón de salida. La herramienta no graba vídeos.','Appuyez sur Play dans la vue d’enregistrement : compte à rebours de 3 secondes. Espace met en pause, Échap quitte. Bougez la souris ou touchez pour afficher le bouton de sortie. Cet outil n’enregistre pas de vidéo.'],
 recovery:['Lokaler Entwurf wiederhergestellt.','Local draft restored.','Borrador local restaurado.','Brouillon local restauré.'],storageError:['Entwurf konnte nicht lokal gespeichert werden. Bitte als Datei speichern.','Could not save draft locally. Please save it as a file.','No se pudo guardar el borrador local. Guarda un archivo.','Impossible de conserver le brouillon local. Enregistrez un fichier.'],
};
export type EditorKey=keyof typeof words;
export function editorDictionary(lang:Language):Record<EditorKey,string>{const index=({de:0,en:1,es:2,fr:3})[lang];return Object.fromEntries(Object.entries(words).map(([k,v])=>[k,v[index]])) as Record<EditorKey,string>;}
