import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';
let bytes:Buffer;
test.beforeAll(async({browser})=>{const page=await browser.newPage();const data=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=160;c.height=90;const ctx=c.getContext('2d')!;ctx.fillStyle='red';ctx.fillRect(0,0,160,90);const stream=c.captureStream(10),rec=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks:Blob[]=[];return await new Promise<number[]>(resolve=>{rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());resolve(Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer())));};rec.start();const timer=setInterval(()=>{ctx.fillStyle=Date.now()%2?'red':'blue';ctx.fillRect(0,0,160,90);},100);setTimeout(()=>{clearInterval(timer);rec.stop();},1600);});});bytes=Buffer.from(data);await page.close();});
async function exported(page:import('@playwright/test').Page){const pending=page.waitForEvent('download');await page.locator('#save-project').click();return JSON.parse(await readFile((await (await pending).path())!,'utf8'));}
test('video gallery, trim preview, shared JSON and project video playback',async({page})=>{
 await page.goto('/en/');await page.locator('#video-file').setInputFiles({name:'clip.webm',mimeType:'video/webm',buffer:bytes});await expect(page.locator('#video-list .asset-row')).toHaveCount(1,{timeout:20000});
 await page.locator('#element-add-menu summary').click();await page.locator('[data-add=video]').click();await expect(page.locator('.video-trim-preview')).toBeVisible();await page.locator('[name=videostart]').fill('.2');await page.locator('[name=videostart]').dispatchEvent('change');await page.locator('[name=videoend]').fill('1');await page.locator('[name=videoend]').dispatchEvent('change');
 const p=await exported(page);expect(Object.keys(p.videos)).toHaveLength(1);expect(p.scenes[0].elements.at(-1).video).toMatchObject({start:.2,end:1,muted:true});
 await page.locator('#project-video').click();await page.locator('#project-video-form [name=videoAsset]').selectOption(Object.keys(p.videos)[0]);await page.locator('#project-video-form [name=loop]').check();await page.locator('#project-video-dialog button[type=submit]').click();
 await page.locator('#scene-form [name=backgroundEnabled]').uncheck();const node=page.locator('.project-video-canvas');await expect(node).toHaveCount(1);await page.locator('#play').click();await expect.poll(()=>node.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.1);await page.locator('#play').click();const at=await node.evaluate((v:HTMLVideoElement)=>v.currentTime);await page.waitForTimeout(250);expect(await node.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(at,1);
 await page.locator('#video-list .asset-thumbnail').click();await expect(page.locator('#video-preview-dialog video')).toBeVisible();await page.locator('#close-video-preview').click();
 const saved=await exported(page);saved.scenes.forEach((s:any)=>{s.duration=.5;s.backgroundEnabled=false;s.elements=[];s.transition='none';});
 await page.locator('#open-json').click();await page.locator('#json-input').fill(JSON.stringify(saved));await page.locator('#import-json').click();await expect(page.locator('#json-dialog')).not.toBeVisible();
 await page.evaluate(()=>{(window as any).videoNode=document.querySelector('.project-video-canvas');});await page.locator('#play').click();await expect.poll(()=>page.locator('.scene-layer').getAttribute('data-scene-index')).toBe('1');expect(await page.evaluate(()=>document.querySelector('.project-video-canvas')===(window as any).videoNode)).toBe(true);
 await expect(page.locator('#play')).toHaveAttribute('title','Play from here');await page.locator('#focus').click();await page.locator('#start-recording').click();await expect(page.locator('#countdown')).toBeVisible();expect(await page.locator('.project-video-canvas').evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);await page.keyboard.press('Escape');

});
