export const clockGuide = {
 de: {
 title:'Kostenlose Online-Uhr – analog, digital und Klappzahlen',
 intro:'Deine Online-Uhr für Schreibtisch, Küche oder einen ruhigen Moment. Analog, digital oder mit Klappzahlen – mit Datum, wählbarer Zeitzone und einem Design, das zu dir passt. Kostenlos und ohne Anmeldung.',
 heading:'Die Zeit im Blick. In deinem Stil.',
 body:'Mach deinen Browser zur gut lesbaren Uhr. Wähle deine Darstellung und blende in der Fokusansicht alles aus, was du gerade nicht brauchst.',
 steps:[['Wähle deine Uhr','Analoges Zifferblatt, digitale Zeit oder animierte Klappzahlen: Du entscheidest. Die analoge Uhr lässt sich auch mit einer der beiden digitalen Ansichten kombinieren.'],['Gestalte deinen Überblick','Ergänze ein Kalenderblatt, eine elegante Datumszeile oder ein Klappdatum. Passe Zeitzone, Sekunden, Farben, Schriftgröße und Hell- oder Dunkelmodus an.'],['Lass der Zeit Raum','Nutze die Fokusansicht und optional Vollbild. Mit „Bildschirm wach halten“ kann die Uhr sichtbar bleiben, sofern Browser und Gerät dies unterstützen.']],
 faq:[['Woher stammt die angezeigte Uhrzeit?','Die Uhr verwendet die Zeit deines Geräts. Sie fragt keinen externen Zeitdienst ab und ist keine unabhängig synchronisierte Atomuhr. Prüfe bei Abweichungen die Datum- und Zeiteinstellungen deines Geräts.'],['Kann ich eine andere Zeitzone anzeigen?','Ja. Standardmäßig gilt die Gerätezeitzone. Im Menü kannst du beispielsweise Berlin, London, New York oder Tokio wählen. Uhrzeit und Datum beziehen sich dann auf diese Zone; Sommerzeit wird nach den Zeitzonendaten deines Browsers berücksichtigt.'],['Welche Uhr- und Datumsansichten gibt es?','Zur Auswahl stehen Analog, Digital, Klappzahlen sowie Analog + Digital und Analog + Klappzahlen. Das Datum kann als Text, Kalenderblatt, elegante Zeile oder Klappdatum erscheinen und auch ausgeblendet werden. Kurz, Mittel und Lang bestimmen das Format der Textanzeige.'],['Funktioniert die Uhr auf dem Smartphone?','Ja, die Ansicht passt sich an kleine Bildschirme an. In der Fokusansicht im Querformat stehen kombinierte Anzeigen nebeneinander. Vollbild und Bildschirm-Wachhalten hängen vom Browser und Gerät ab und verhindern keine manuelle Bildschirmsperre.'],['Werden meine Einstellungen gespeichert?','Nur wenn du „Einstellungen auf diesem Gerät merken“ aktivierst. Die Einstellungen bleiben lokal in diesem Browser. Du kannst die Speicherung ausschalten oder unter „Lokale Einstellungen“ löschen. Die Uhr bindet keine Werbung oder Tracking-Skripte ein.']]
 },
 en: {
 title:'Free online clock – analog, digital and flip clock',
 intro:'An online clock for your desk, kitchen or a quiet moment. Choose analog, digital or flip digits, with a date, selectable time zone and your own visual style. Free, with no account needed.',
 heading:'Time at a glance. In your style.',body:'Turn your browser into an easy-to-read clock. Choose your display and use focus view to hide distractions.',
 steps:[['Choose your clock','Pick an analog dial, digital time or animated flip digits. You can also combine the analog clock with either digital display.'],['Make it yours','Add a calendar card, elegant date line or flip date. Adjust the time zone, seconds, colours, font size and light or dark mode.'],['Give time some space','Use focus view and optional fullscreen. “Keep screen awake” can keep your clock visible when supported by your browser and device.']],
 faq:[['Where does the time come from?','The clock uses your device time. It does not query an external time service and is not an independently synchronised atomic clock. Check your device date and time settings if the time is incorrect.'],['Can I display another time zone?','Yes. Your device time zone is the default. Choose a zone such as Berlin, London, New York or Tokyo in the menu. Both time and date follow that zone, including daylight saving changes according to your browser’s time zone data.'],['Which clock and date styles are available?','Choose Analog, Digital, Flip clock, Analog + Digital or Analog + Flip clock. Show the date as text, a calendar card, an elegant line or flip digits, or hide it. Short, Medium and Long control the text date format.'],['Does it work on a phone?','Yes, the layout adapts to small screens. Combined displays sit side by side in landscape focus view. Fullscreen and keeping the screen awake depend on your browser and device and do not prevent manual screen locking.'],['Are my settings saved?','Only if you enable “Remember settings on this device”. Preferences stay locally in this browser. Disable storage or delete them under “Local settings”. The clock embeds no advertising or tracking scripts.']]
 },
 es: {
 title:'Reloj online gratis – analógico, digital y de láminas',intro:'Un reloj para tu escritorio, cocina o un momento tranquilo. Elige una vista analógica, digital o de láminas, con fecha, zona horaria y diseño personal. Gratis y sin registro.',heading:'La hora a tu vista. A tu estilo.',body:'Convierte tu navegador en un reloj fácil de leer. Elige una vista y elimina distracciones con el modo de enfoque.',
 steps:[['Elige tu reloj','Usa una esfera analógica, números digitales o láminas animadas. También puedes combinar la esfera con cualquiera de las dos vistas digitales.'],['Personaliza la vista','Añade una hoja de calendario, una fecha elegante o de láminas. Ajusta zona horaria, segundos, colores, tamaño de letra y modo claro u oscuro.'],['Deja espacio al tiempo','Activa el modo de enfoque y, si quieres, pantalla completa. Mantener la pantalla encendida depende de la compatibilidad del navegador y del dispositivo.']],
 faq:[['¿De dónde procede la hora?','Usamos la hora de tu dispositivo, sin consultar servicios externos. No es un reloj atómico sincronizado de forma independiente. Si hay diferencias, revisa la configuración de fecha y hora de tu dispositivo.'],['¿Puedo cambiar la zona horaria?','Sí. Por defecto se usa la del dispositivo. Puedes elegir Berlín, Londres, Nueva York o Tokio, entre otras. La fecha y la hora se adaptan a esa zona, incluido el horario de verano según los datos del navegador.'],['¿Qué vistas están disponibles?','Analógica, digital, de láminas y combinaciones de analógica con digital o láminas. La fecha puede mostrarse como texto, calendario, línea elegante o láminas, u ocultarse. Corto, Medio y Largo determinan el formato de fecha en texto.'],['¿Funciona en el móvil?','Sí. El diseño se adapta a pantallas pequeñas. En enfoque horizontal, las vistas combinadas aparecen una junto a otra. La pantalla completa y mantenerla encendida dependen del navegador y dispositivo; no impiden el bloqueo manual.'],['¿Se guardan mis ajustes?','Solo si activas “Recordar ajustes en este dispositivo”. Se guardan localmente en este navegador. Puedes desactivar el almacenamiento o borrarlos en “Ajustes locales”. El reloj no incorpora publicidad ni scripts de rastreo.']]
 },
 fr: {
 title:'Horloge en ligne gratuite – analogique, numérique et à palettes',intro:'Une horloge pour votre bureau, votre cuisine ou un moment calme. Analogique, numérique ou à palettes, avec date, fuseau horaire et style personnalisables. Gratuite et sans inscription.',heading:'L’heure en un regard. À votre façon.',body:'Transformez votre navigateur en horloge facile à lire. Choisissez votre affichage et masquez les distractions avec la vue concentration.',
 steps:[['Choisissez votre horloge','Cadran analogique, chiffres numériques ou palettes animées : à vous de choisir. Combinez aussi le cadran avec l’un des deux affichages numériques.'],['Personnalisez votre vue','Ajoutez un feuillet de calendrier, une date élégante ou à palettes. Réglez fuseau horaire, secondes, couleurs, taille du texte et mode clair ou sombre.'],['Faites place au temps','Utilisez la vue concentration et le plein écran facultatif. Le maintien de l’écran allumé est disponible si votre navigateur et votre appareil le permettent.']],
 faq:[['D’où vient l’heure affichée ?','L’horloge utilise l’heure de votre appareil sans interroger de service externe. Ce n’est pas une horloge atomique synchronisée indépendamment. En cas d’écart, vérifiez les réglages de date et d’heure de votre appareil.'],['Puis-je choisir un autre fuseau horaire ?','Oui. Le fuseau de votre appareil est utilisé par défaut. Choisissez notamment Berlin, Londres, New York ou Tokyo. La date et l’heure suivent ce fuseau, y compris les changements d’heure selon les données de votre navigateur.'],['Quels affichages sont disponibles ?','Analogique, numérique, palettes et combinaisons analogique + numérique ou palettes. La date peut être du texte, un calendrier, une ligne élégante ou des palettes, ou être masquée. Court, Moyen et Long règlent le format de la date textuelle.'],['L’horloge fonctionne-t-elle sur téléphone ?','Oui, la présentation s’adapte aux petits écrans. En vue concentration horizontale, les affichages combinés sont côte à côte. Le plein écran et le maintien de l’écran allumé dépendent du navigateur et de l’appareil et ne bloquent pas le verrouillage manuel.'],['Mes réglages sont-ils enregistrés ?','Seulement si vous activez « Mémoriser les réglages sur cet appareil ». Ils restent localement dans ce navigateur. Désactivez le stockage ou supprimez-les dans « Réglages locaux ». Aucun script publicitaire ou de suivi n’est intégré à l’horloge.']]
 }
};
